name: Deploy Portfolio Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/my-cv
            git pull
            docker stop my-cv-container || true
            docker rm my-cv-container || true
            docker build -t my-cv-image .
            docker run -d --name my-cv-container -p 8080:80 --restart unless-stopped my-cv-image
            docker image prune -f